const BASE={budget:650,schedule:0,support:50,scope:0,risk:0};
const decisions=[
{id:'D1',stage:'Pre-initiation',title:'Who should sponsor the project?',hint:'Choose the person with enough authority to champion the project, while accepting the trade-off that comes with that profile.',facts:'Given: Mourouj is the fixed location. Target opening: 01 Jul 2027. Preliminary ceiling: 650,000 TND. The project has passed formal selection; sponsor is not yet assigned.',opts:[['General Manager','Highest authority and strong escalation power, but limited time.','gm'],['Head of Development','Strong expansion experience and investment focus, but less involved in daily operations.','dev'],['Operations Director','Strong knowledge of service and brand standards, but less investment experience.','ops']],effect:(s,o)=>({support:o==='gm'?4:o==='dev'?2:3,risk:o==='gm'?0:o==='dev'?1:0}),conseq:o=>`Sponsor selected: ${label(o)}. The choice changes who can champion and escalate the project; it does not change the initial budget or date.`},
{id:'D2',stage:'Pre-initiation',title:'Who should be Project Manager?',hint:'The PM needs enough project-management capacity to coordinate the work and meet the organization’s expectations.',facts:'Chapter 3 task: select the project manager and review organizational expectations. Monthly reporting to a steering committee is expected in this simulation.',opts:[['Existing branch manager','Knows Barista standards and operations, but may be stretched by the project.','branch'],['External project consultant','Neutral and methodical, but needs to learn Barista culture and standards.','consult'],['Area manager','Has authority across branches, but must divide attention between locations.','area']],effect:(s,o)=>({support:o==='branch'?2:0,risk:o==='consult'?2:1,schedule:o==='consult'?1:0}),conseq:o=>`PM selected: ${label(o)}. The trade-off is capacity and neutrality versus direct knowledge of Barista operations.`},
{id:'D3',stage:'Pre-initiation',title:'How should the project be divided?',hint:'Chapter 3 asks whether a project should be divided into smaller projects. Choose the structure that gives the class a manageable initiation boundary.',facts:'The team must keep scope realistic. A single branch opening can be managed as one project, or separated into study / fit-out / readiness workstreams.',opts:[['One integrated project','One accountable project from initiation through opening.','one'],['Study then opening','Phase I validates the Mourouj opportunity before Phase II fit-out and opening.','two'],['Three coordinated projects','Separate study, fit-out and operations-readiness work.','three']],effect:(s,o)=>({budget:o==='two'?40:o==='three'?55:0,schedule:o==='two'?1:o==='three'?2:0,support:o==='two'?2:o==='three'?1:0,risk:o==='three'?2:o==='two'?1:0}),conseq:o=>`Project structure: ${label(o)}. More separation can improve control, but coordination adds time and management overhead.`},
{id:'D4',stage:'Business case',title:'Which option should the business case recommend?',hint:'Compare alternatives against control, investment exposure, capacity and brand consistency. These are fictional classroom assumptions.',facts:'Simulation assumptions: Company-owned = 650k TND / 3.5-year payback; franchise = 400k / 2.5 years; smaller-format = 450k / 2.8 years. These are NOT Barista financial data.',opts:[['Company-owned branch','Maximum direct control over quality and customer experience; highest investment.','own'],['Franchisee branch','Lower direct investment and faster assumed payback; less direct control over execution.','franchise'],['Smaller-format branch','Lower assumed investment and risk; lower capacity and proposition breadth.','small']],effect:(s,o)=>({budget:o==='franchise'?-250:o==='small'?-200:0,support:o==='own'?3:o==='franchise'?-2:1,risk:o==='franchise'?2:o==='small'?-1:0}),conseq:o=>`Recommended option: ${label(o)}. The business case now has a direction, but the financial figures remain fictional simulation assumptions.`},
{id:'D5',stage:'Business case',title:'What should be the secondary objective?',hint:'The primary objective remains: open on time, within budget and to Barista-standard quality.',facts:'Primary objective is fixed for the simulation. Choose one secondary objective to shape later trade-offs.',opts:[['Strengthen presence among young customers','Prioritizes reach and local customer appeal.','young'],['Protect brand consistency','Prioritizes consistency across the customer experience.','brand'],['Fastest payback','Prioritizes investment recovery.','payback']],effect:(s,o)=>({support:o==='young'?5:o==='brand'?2:-1,risk:o==='payback'?1:0}),conseq:o=>`Secondary objective: ${label(o)}. This becomes a lens for interpreting later scope and stakeholder choices.`},
{id:'D6',stage:'Stakeholders',title:'How broadly should stakeholders be engaged now?',hint:'Chapter 3 emphasizes identifying and understanding stakeholders. The question is how much engagement is appropriate at initiation.',facts:'Stakeholders include HQ/top management, project roles, future branch staff, Mourouj customers, suppliers, municipality/permit officials, neighbours and competitors.',opts:[['Broad early engagement','Engage users, local stakeholders and key internal functions from the start.','broad'],['Targeted engagement','Prioritize high-influence/high-interest stakeholders first.','targeted'],['Minimal engagement','Keep the initiation group small and consult others later.','minimal']],effect:(s,o)=>({support:o==='broad'?8:o==='targeted'?4:-5,risk:o==='broad'?-2:o==='targeted'?0:2}),conseq:o=>`Stakeholder strategy: ${label(o)}. The decision updates both the stakeholder management strategy and the project’s support/risk outlook.`},
{id:'D7',stage:'Scope',title:'What should be included in the opening scope?',hint:'Core branch capabilities are mandatory. The class decides which optional components to add.',facts:'Fixed core: brand-standard fit-out, permits, espresso service, seating, Wi-Fi, payment, hygiene. Optional components: hot kitchen, terrace, Glovo delivery, launch social campaign.',opts:[['Core only','Keep the opening proposition focused and protect the baseline.','core'],['Core + selected growth features','Add any two of: kitchen, terrace, Glovo, launch campaign.','selected'],['Full launch package','Add kitchen + terrace + Glovo + launch campaign.','full']],effect:(s,o)=>{let add=o==='core'?0:o==='selected'?3:5;return {scope:add,budget:add*35,schedule:add*0.7,support:o==='full'?6:o==='selected'?3:0,risk:add>=5?2:add>=3?1:0}},conseq:o=>`Scope choice: ${label(o)}. More scope increases the value proposition, but it consumes budget and schedule capacity.`},
{id:'D8',stage:'Constraints',title:'Which constraint should receive priority when trade-offs appear?',hint:'There is no universally correct answer. The class is choosing what the project protects first.',facts:'Simulation boundaries: budget ceiling 650k TND with a +10% tolerance (715k max), target opening 01 Jul 2027 with a maximum +4-week tolerance. Scope is the most flexible when time and cost are fixed.',opts:[['Protect opening date','Favor speed; scope may be reduced and/or cost pressure may rise.','time'],['Protect budget','Avoid overspend; scope may be reduced and schedule may move.','budget'],['Protect planned scope','Preserve the selected proposition; budget and schedule carry more pressure.','scope']],effect:(s,o)=>({budget:o==='time'?25:o==='scope'?20:0,schedule:o==='budget'?1.5:o==='scope'?1:0,support:o==='scope'?2:0,risk:o==='time'?1:o==='scope'?2:0}),conseq:o=>`Priority set to ${label(o)}. This rule will be used when the simulator detects tension between scope, cost and schedule.`},
{id:'D9',stage:'Approach',title:'Which project approach should the charter record?',hint:'Choose how internal expertise and external capacity are balanced.',facts:'Approach options: internal-led, outsourced fit-out, or mixed internal/outsourced labor. Each affects control, speed and coordination.',opts:[['Internal-led','Operations leads design, fit-out and staffing; strongest internal knowledge, slower capacity.','internal'],['Outsourced fit-out','Contractors execute fit-out while Barista supervises and trains; faster capacity, less direct control.','outsource'],['Mixed internal / outsourced','Split work to balance internal standards with external execution capacity.','mixed']],effect:(s,o)=>({budget:o==='outsource'?-10:o==='mixed'?-5:0,schedule:o==='outsource'?-1:o==='mixed'?-0.5:1,support:o==='internal'?3:o==='mixed'?2:0,risk:o==='outsource'?2:o==='mixed'?0:0}),conseq:o=>`Approach recorded: ${label(o)}. The choice affects the project’s ability to absorb the selected scope and deadline.`},
{id:'D10',stage:'Kick-off',title:'At kick-off, should the class confirm the current scope?',hint:'The kick-off is where key stakeholders review the business case, charter, organization and scope/time/cost goals.',facts:'The draft charter is assembled from your decisions. If scope does not fit the current budget/date, the project can be clarified before moving forward.',opts:[['Confirm current scope','Proceed with the current charter boundary.','confirm'],['Reduce scope before approval','Remove optional elements to restore feasibility.','reduce'],['Pause for clarification','Return to the charter and resolve the main conflict first.','pause']],effect:(s,o)=>{if(o==='reduce')return {scope:-2,budget:-70,schedule:-1,support:1,risk:-2};if(o==='pause')return {schedule:2,risk:-1,support:0};return {support:2,risk:s.budget>715?2:0}},conseq:o=>`Kick-off decision: ${label(o)}. A confirmation keeps momentum; rework choices trade time for a more coherent charter.`},
{id:'D11',stage:'Kick-off',title:'What should be clarified before the meeting closes?',hint:'Roles and responsibilities are a core kick-off purpose. Choose the immediate emphasis.',facts:'The kick-off reviews organizational structure, scope/time/cost goals, major risks and action items. The champion should introduce the sponsor and PM first.',opts:[['Roles + responsibilities','Confirm who owns decisions, reporting and key deliverables.','roles'],['Immediate action items','Leave the meeting with tasks and deadlines as the first priority.','actions'],['Both, with roles first','Align ownership, then convert gaps into action items.','both']],effect:(s,o)=>({support:o==='both'?4:o==='roles'?3:1,risk:o==='both'?-2:o==='roles'?-1:0}),conseq:o=>`Kick-off emphasis: ${label(o)}. Clear ownership improves coordination; action items convert alignment into execution.`},
{id:'D12',stage:'Kick-off',title:'Should a brand audit be added before opening?',hint:'This is a final governance choice: add a quality gate or preserve the current path to opening.',facts:'Simulation success criterion: brand audit ≥90%. The audit itself is a fictional governance mechanism for the classroom simulation.',opts:[['Yes — add the audit gate','Add a pre-opening quality check; may create a small schedule buffer requirement.','yes'],['No — rely on standard controls','Avoid a new gate; keep the existing opening path.','no']],effect:(s,o)=>({schedule:o==='yes'?0.5:0,risk:o==='yes'?-2:1,support:o==='yes'?3:0}),conseq:o=>`Brand-audit choice: ${label(o)}. The final evaluation will consider the resulting quality-control risk alongside budget and schedule.`}
];
const labels={gm:'General Manager',dev:'Head of Development',ops:'Operations Director',branch:'Existing branch manager',consult:'External project consultant',area:'Area manager',one:'One integrated project',two:'Study then opening',three:'Three coordinated projects',own:'Company-owned branch',franchise:'Franchisee branch',small:'Smaller-format branch',young:'Strengthen presence among young customers',brand:'Protect brand consistency',payback:'Fastest payback',broad:'Broad early engagement',targeted:'Targeted engagement',minimal:'Minimal engagement',core:'Core only',selected:'Core + selected growth features',full:'Full launch package',time:'Protect opening date',budget:'Protect budget',scope:'Protect planned scope',internal:'Internal-led',outsource:'Outsourced fit-out',mixed:'Mixed internal / outsourced',confirm:'Confirm current scope',reduce:'Reduce scope before approval',pause:'Pause for clarification',roles:'Roles + responsibilities',actions:'Immediate action items',both:'Both, with roles first',yes:'Yes — add the audit gate',no:'No — rely on standard controls'};
function label(x){return labels[x]||x}
let state={...BASE,answers:{},logs:[],selected:null,current:0};
const $=id=>document.getElementById(id);
function riskLevel(){if(state.risk>=7)return ['High','high'];if(state.risk>=3)return ['Medium','medium'];return ['Low','low']}
function formatDate(days){let d=new Date('2027-07-01T00:00:00');d.setDate(d.getDate()+Math.round(days));return d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function render(){const d=decisions[Math.min(state.current, decisions.length-1)];$('stageLabel').textContent=`STAGE ${Math.min(8,Math.floor(state.current/2)+1)}`;$('stageTitle').textContent=d.stage;$('stageCount').textContent=`${Math.min(8,Math.floor(state.current/2)+1)} / 8`;$('progressBar').style.width=`${(state.current/decisions.length)*100}%`;
const notes={"Pre-initiation":'Determine constraints, sponsor, project manager and organizational expectations before formal initiation.',"Business case":'Define the business need, alternatives, assumptions, risks and recommendation.',Stakeholders:'Identify people affected by the project and build a stakeholder management strategy.',Scope:'Turn the business need into a realistic project boundary.',Constraints:'Make the scope–time–cost trade-off explicit.',Approach:'Choose how the project will be organized and executed.',"Kick-off":'Use the business case and charter to align stakeholders, roles, scope, time and cost.'};$('chapterNote').textContent=notes[d.stage]||'';
$('questionNumber').textContent=d.id;$('question').textContent=d.title;$('questionHint').textContent=d.hint;$('givenFacts').textContent=d.facts;
$('options').innerHTML=d.opts.map((o,i)=>`<div class="option ${state.selected===o[2]?'selected':''}" data-v="${o[2]}"><div class="option-title">${String.fromCharCode(65+i)} · ${o[0]}</div><div class="option-copy">${o[1]}</div></div>`).join('');document.querySelectorAll('.option').forEach(el=>el.onclick=()=>{state.selected=el.dataset.v;render()});$('voteBtn').disabled=!state.selected || state.current>=decisions.length;$('decisionMini').textContent=`${Math.min(state.current, decisions.length)} / ${decisions.length}`;
$('scopeMetric').textContent=state.scope===0?'Core':`${state.scope} add-ons`;$('scopeBar').style.width=`${Math.min(100,30+state.scope*12)}%`;$('budgetMetric').textContent=`${Math.round(state.budget)}k TND`;$('budgetBar').style.width=`${Math.min(100,Math.max(5,state.budget/7.15))}%`;$('scheduleMetric').textContent=formatDate(state.schedule);$('scheduleBar').style.width=`${Math.min(100,Math.max(8,70-state.schedule*12))}%`;$('supportMetric').textContent=`${Math.round(state.support)} / 100`;$('supportBar').style.width=`${Math.max(0,Math.min(100,state.support))}%`;const [rl,rc]=riskLevel();$('riskMetric').textContent=rl;$('riskPill').textContent=rl.toUpperCase();$('riskPill').className=`risk-pill ${rc}`;
$('decisionLog').innerHTML=state.logs.length?state.logs.map(x=>`<div class="log-item"><span class="log-id">${x.id}</span><b>${x.choice}</b><small>${x.consequence}</small></div>`).join(''):'<div class="empty">Decisions will appear here as the class progresses.</div>';
$('docBusiness').textContent=state.current>=4?'Built from scenario decisions':'In progress';$('docStake').textContent=state.current>=6?'Generated':'Not generated';$('docStrategy').textContent=state.current>=6?'Generated':'Not generated';$('docRisk').textContent=state.current?'Updating from decisions':'Initial risks loaded';
if(state.current>=10){$('charterSection').classList.remove('hidden');renderCharter()}else $('charterSection').classList.add('hidden');
if(state.current>=decisions.length){renderFinal()}else $('finalSection').classList.add('hidden')}
function renderCharter(){const vals=[['Project identity','Barista Mourouj Branch Opening Project'],['Start / target','04 Jan 2027 → '+formatDate(state.schedule)],['Sponsor',label(state.answers.D1)],['Project Manager',label(state.answers.D2)],['Business objective','Open on time, within budget and to Barista-standard quality'],['Secondary objective',label(state.answers.D5)],['Recommended option',label(state.answers.D4)],['Scope',label(state.answers.D7)],['Constraint priority',label(state.answers.D8)],['Approach',label(state.answers.D9)],['Budget estimate',Math.round(state.budget)+'k TND (simulation)'],['Success criteria','Opening by target tolerance · spend ≤715k · brand audit ≥90%'],['Stakeholder strategy',label(state.answers.D6)],['Major risks',riskLevel()[0]+' overall · fit-out delay · cost overrun · quality / hiring / permits'],['Sign-off','Sponsor + key stakeholders approve charter before project execution']];$('charterGrid').innerHTML=vals.map(v=>`<div class="charter-item"><small>${v[0]}</small><b>${v[1]}</b></div>`).join('');$('statusChip').textContent=state.current>=decisions.length?'FINAL':'DRAFT'}
function apply(o){
  if(!o || state.current>=decisions.length) return;
  const d=decisions[state.current];
  const consequence=d.conseq(o);
  const e=d.effect(state,o);
  for(const [k,v] of Object.entries(e)){state[k]+=v}
  state.answers[d.id]=o;
  state.logs.push({id:d.id,choice:label(o),consequence});
  state.current++;
  state.selected=null;
  // Render the next decision first, then show the consequence of the vote just recorded.
  render();
  $('consequence').classList.remove('hidden');
  $('consequence').innerHTML=`<b>CONSEQUENCE</b><br>${consequence}`;
  if(state.current<decisions.length){
    $('consequence').scrollIntoView({behavior:'smooth',block:'nearest'});
  } else {
    // Final decision: make the completed state immediately visible and scroll to it.
    $('finalSection').scrollIntoView({behavior:'smooth',block:'start'});
  }
}
$('voteBtn').onclick=()=>{
  if(!state.selected || state.current>=decisions.length) return;
  const choice=state.selected;
  $('voteBtn').disabled=true;
  apply(choice);
};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.tab-content').forEach(x=>x.classList.add('hidden'));$(`tab-${t.dataset.tab}`).classList.remove('hidden')});
$('restartBtn').onclick=()=>{state={...BASE,answers:{},logs:[],selected:null,current:0};render();window.scrollTo({top:0,behavior:'smooth'})};
function finalStatus(){let over=state.budget>715||state.schedule>28||state.answers.D12==='no'&&state.risk>=7; if(over)return ['REWORK REQUIRED','rework'];if(state.risk>=7||state.support<45||state.budget>690||state.schedule>21)return ['AT RISK','at-risk'];return ['ON TRACK','']}
function renderFinal(){const [st,cl]=finalStatus();$('finalSection').classList.remove('hidden');$('finalStatus').textContent=st;$('finalStatus').className=`final-status ${cl}`;$('finalTitle').textContent=st==='ON TRACK'?'Project evaluation: viable path':st==='AT RISK'?'Project evaluation: pressure is building':'Project evaluation: charter needs rework';$('finalNarrative').textContent=`The class did not “win” by selecting correct answers. The project outcome reflects the accumulated trade-offs between scope, budget, schedule, stakeholder support and risk.`;$('finalMetrics').innerHTML=[['Scope',label(state.answers.D7)],['Budget',Math.round(state.budget)+'k TND'],['Schedule',formatDate(state.schedule)],['Support',Math.round(state.support)+'/100'],['Risk',riskLevel()[0]],['Mandatory gate',state.answers.D12==='yes'?'Brand audit added':'Standard controls only']].map(x=>`<div class="final-box"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');let impacts=decisions.map(d=>{let idx=Object.keys(state.answers).indexOf(d.id);let score=d.id==='D7'?Math.abs(state.scope)*4:d.id==='D4'?Math.abs(state.budget-650):d.id==='D6'?Math.abs(state.support-50)*2:d.id==='D8'?10:d.id==='D9'?8:d.id==='D10'?9:d.id==='D12'?8:5;return [score,d]});impacts.sort((a,b)=>b[0]-a[0]);$('driversList').innerHTML=impacts.slice(0,3).map(x=>`<li><b>${x[1].id} — ${x[1].title}</b><br><span>${label(state.answers[x[1].id])}</span></li>`).join('');$('whatIfBtn').onclick=()=>{let alt=state.budget;let delta=state.answers.D7==='full'?-105:state.answers.D7==='core'?105:70;$('whatIf').classList.remove('hidden');$('whatIf').innerHTML=`<b>What if the scope decision changed?</b><br>Current simulated budget: ${Math.round(state.budget)}k TND. A different scope choice would shift the budget and schedule in this classroom model; the point is to compare trade-offs, not identify a single correct decision.`}}
render();
